# Generated by Django 4.2.3 on 2023-08-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_customuser'),
        ('MyTasks', '0002_alter_task_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
