# Generated by Django 4.2.3 on 2023-08-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
